FROM node:12.13 as build

WORKDIR /app

COPY package*.json tsconfig.json ./
COPY src ./src/
COPY public ./public/

RUN npm ci

RUN npm run build

FROM nginx:1.17

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
