version: "3.7"

services:
  api:
    image: stevecshanks/next-actions-api:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - TRELLO_BASE_URL=https://api.trello.com/1
      - TRELLO_KEY=${TRELLO_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_NEXT_ACTIONS_LIST_ID=${TRELLO_NEXT_ACTIONS_LIST_ID}
      - TRELLO_PROJECTS_LIST_ID=${TRELLO_PROJECTS_LIST_ID}
  frontend:
    image: stevecshanks/next-actions-frontend:latest
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - frontend
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${SERVER_NAME}
volumes:
  certbot-etc:
  certbot-var:
