version: "3.7"

services:
  api:
    build: api
    image: api
    ports:
      - 8080:8080
    volumes:
      - ./api:/go/src/next-actions/api
    environment:
      - TRELLO_BASE_URL=https://api.trello.com/1
      - TRELLO_KEY=${TRELLO_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
  frontend:
    build: frontend
    depends_on:
      - api
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./frontend:/app
      - /app/node_modules
