version: "3.7"

services:
  api:
    image: stevecshanks/next-actions-api:latest
    ports:
      - 8080:8080
    restart: always
  frontend:
    image: stevecshanks/next-actions-frontend:latest
    depends_on:
      - api
    ports:
      - 80:80
    restart: always
