version: 2
jobs:
  frontend_tests:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  api_tests:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo/api
    steps:
      - checkout:
          path: ~/repo
      - run: go test
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo
      - run: make deploy
workflows:
  version: 2
  everything:
    jobs:
      - frontend_tests
      - api_tests
      - deploy:
          requires:
            - frontend_tests
            - api_tests
          filters:
            branches:
              only: master
