version: 2
jobs:
  frontend_tests:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo/frontend
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  api_tests:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/next-actions
    steps:
      - checkout:
          path: /go/src/next-actions
      - run: make go_tests
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout:
          path: ~/repo
      - run: mkdir -p ~/.ssh
      - run: echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - run: chmod 644 ~/.ssh/known_hosts
      - run: make build push deploy
workflows:
  version: 2
  everything:
    jobs:
      - frontend_tests
      - api_tests
      - deploy:
          requires:
            - frontend_tests
            - api_tests
          filters:
            branches:
              only: master
